### PR TITLE
Fixes #301: Add Celery job to send remainders

### LINKED ISSUE #301: Add Celery job to send remainders
We need to add celery job to
1) send Intro email 7 days before the workshop dates
2) Remainder Email 2 days before workshop
3) Feedback email on workshop day
4) Remainder of Feedback email after 2 days of workshop.

### PR DESCRIPTION
**Pull request by lavish205**
#301

### CODE REVIEW

**Comment by lavish205** [comment]
@vnbang2003 r?

**Comment by lavish205** [comment]
@vnbang2003 all test cases are passed, I don't know why travis is failing.
Can you please verify?

**Comment by vnbang2003** [comment]
@lavish205 pep8 bug is been fixed i guess update your local with latest code.

**Comment by aniketmaithani** [comment]
@lavish205 
```
./wye/reports/views.py:8:1: F401 'Profile' imported but unused
./wye/reports/views.py:39:1: W293 blank line contains whitespace
``` 
Check this in your code :) FLAKE8 issues :)

**Comment by vnbang2003** [comment]
@lavish205 Last thing Testcase to support your changes.

**Comment by vnbang2003** [comment]
@lavish205 It been long time pending can we do needful for Pull request . We need this fix asap.

**Comment by vnbang2003** [comment]
@lavish205 Any update on this . It been pending long time

**Comment by vnbang2003** [comment]
@lavish205  Are you still on it . I am planning to close this before sunday.
If you are not able to make progress shall i take up and complete it.

**Comment by lavish205** [comment]
Hi @vnbang2003, sorry for the delay, you can take this up.

**Pull request closed without merging**
