### PR TITLE
fix query for regional lead in workshoplist view

### PR DESCRIPTION
**Pull request by shankisg**
Addresses #220  issue.

I have fix the query for regional lead in WorkshopList view.

### CODE REVIEW

**Comment by vnbang2003** [comment]
@shankisg Can we add test case also ? This pull request is reducing coverage ?

**Comment by vnbang2003** [comment]
@shankisg I explain how test work in our system, Can you please do the needful for this PR.
https://github.com/pythonindia/wye/issues/218

Let make this product more stable by add more test cases.

**Comment by shankisg** [comment]
Ok let me check

**Comment by vnbang2003** [comment]
@shankisg any luck with this ?

**Comment by shankisg** [comment]
@vnbang2003 while writing test for WorkshopList view, came up with some question.

- For listing workshop, current logic checks if user is presenter, requester or regional lead and displays works accordingly. But if, user is not any of the type it lists all workshop? Is this fine.

- To keep the test scripts clean/handy, I want to create folder named workshop inside **tests/functional/** and put all workshop related testcase in this folder. What you say.

**Comment by vnbang2003** [comment]
For listing workshop, current logic checks if user is presenter, requester or regional lead and displays works accordingly. But if, user is not any of the type it lists all workshop? Is this fine.
>> Out system presently doesn't allow other user type but it good to add testcase to handle it also.

    To keep the test scripts clean/handy, I want to create folder named workshop inside tests/functional/ and put all workshop related testcase in this folder. What you say.
:+1:

**Comment by shankisg** [comment]
@vnbang2003 could pls check why py.test failed. In my local it worked fine.

**Comment by vnbang2003** [comment]
@shankisg  build was failing hence it was creating problem.
Can you update you code base as presently we are in 82 and you code increase 4.8 but still it show 82.

**Comment by vnbang2003** [comment]
@shankisg Can you confirm if functionality is achieved. I will merge this pull request.

**Comment by shankisg** [comment]
@vnbang2003 yes it's working. Also in my local environment all tests are successfully.

**Pull request merged**
