### PR TITLE
Profiles: Convert Contact Us CBV to FBV

### PR DESCRIPTION
**Pull request by staranjeet**
This PR converts Contact Us class based view to a function based view as per issue #256

### CODE REVIEW

**Comment by vnbang2003** [comment]
@staranjeet Can you please take care of build issue ?

**Comment by staranjeet** [comment]
@vnbang2003: How can I fix this error ?
```
AttributeError: 'module' object has no attribute 'hookimpl'
```

**Comment by theskumar** [comment]
It seems to be due to some old version of py.test, this is thing was introduced in py.test==2.8.0, i'll try to look into it.

> pluginmanagement: introduce pytest.hookimpl and pytest.hookspec decorators for setting impl/spec specific parameters. This substitutes the previous now deprecated use of pytest.mark which is meant to contain markers for test functions only.

http://pytest.org/latest/changelog.html#id19

**Comment by theskumar** [comment]
I've fixed the test in `master` can you rebase your branch from it and that should resolve the issue.

**Comment by staranjeet** [comment]
any updates here?

**Pull request merged**
