### PR TITLE
Fix to move on hold workshops to requested

### PR DESCRIPTION
**Pull request by shubhamgupta2021**

### CODE REVIEW

**Comment by vnbang2003** [comment]
@shubhamgupta2021 Can't accept pull request which reduces testcase. Do have a look and do the needful

**Comment by shubhamgupta2021** [comment]
@vnbang2003, Please have a look now.

**Comment by vnbang2003** [comment]
@shankisg Can you review this change of code as you initial wrote the code ?

**Comment by shubhamgupta2021** [comment]
Apologies. I messed this up, I forgot that I have an open pull request, so this pull request contains commit for other issue also.

**Comment by shubhamgupta2021** [comment]
@shankisg, please review.

**Comment by vnbang2003** [comment]
@shankisg Can you please review the change so we can close this PR.

**Comment by vnbang2003** [comment]
@shubhamgupta2021 I have one comment 'request' is keyword and can create confusion. 
Can we use other work I don't have suggestion now. 
Apart from that it looks good to me.

**Comment by shubhamgupta2021** [comment]
@vnbang2003 Since we are showing request/publish in the button so we can use publish instead of request

**Comment by vnbang2003** [comment]
@shubhamgupta2021 :+1:

**Comment by shubhamgupta2021** [comment]
@vnbang2003 Will update it, this weekend.

**Comment by shubhamgupta2021** [comment]
@vnbang2003, I have made the required changes.

**Pull request merged**
