### PR TITLE
Wye 7

### PR DESCRIPTION
**Pull request by shankig**
Features implemented for Workshop as below. Also workshop model is registered to admin. I have added template for workshops app no css/js, just for testing which will be modified by template designed . Pull the code and access the urls mentioned below.

- list  (http://127.0.0.1:8000/workshop/)
- detail (http://127.0.0.1:8000/workshop/1)
- create (http://127.0.0.1:8000/workshop/create)
- update (http://127.0.0.1:8000/workshop/update/1)
- delete (http://127.0.0.1:8000/workshop/delete/1)

Note: While creating/update workshop presenter field will not be displayed. From admin we can assigned presenter(s) to workshop.

Why presenter is not displayed for create/update workshop ?
 - Per my understanding, creator of workshop are mostly organisation and they are no suppose to know who is presenter while performing the action.

### CODE REVIEW

**Comment by vnbang2003** [comment]
@shankig 
Correct my understand
1) Each workshop request is by default assigned to admin(I think it should be unassigned state right)
2) There is not delete option only deactivate option.

**Comment by shankig** [comment]
@vnbang2003 
While creating workshop, no presenter is assigned. Currently from admin panel it could be assigned to presenter.

Per #28 create/update/delete, I have implemented delete functionality. But I can change it to deactivate, for this I need to add is_active/deactive attribute to workshop model. let me know which attribute is fine for you.

**Comment by vnbang2003** [comment]
+1 for add is_active fields.
workshop requested are pulled by tutor himself . We don't want person to assign.
Example: Say 1 workshop request was made. You as tutor should able to assign to youself.
 
Admin come in picture if he find no taker for workshop where he make few phone call and assign workshop to one of the tutor.

**Comment by shankig** [comment]
Will implement deactive logic and update here.

For " tutor should able to assign to yourself." this feature will come with implementation with #8 , I can take it up.

**Comment by shankig** [comment]
@vnbang2003 
I have implemented the activate and deactivate logic. Also removed delete feature

Sample url for activate and deactivate as below, needed to be called as POST request
http://127.0.0.1:8000/workshop/active/1
http://127.0.0.1:8000/workshop/deactive/1

**Pull request merged**
