### PR TITLE
 Removing fields from signup page. Changing login flow

### PR DESCRIPTION
**Pull request by ultimatecoder**
* **Description:** Removing fields such as User type, location, Interested Sections, Interested Locations from the signup page. First time user will be redirected to Profile Edit page (As Profile is created when User is created so no need for create view here) and User who is having profile information will be redirected to **Dashboard**.

* **Flow**: 
1 User-Signup
2 Conform Mail
3 Login in from Email, Password
4 If User-type is null Go to Step 6 otherwise Go to Next step
5 Redirect to Dashboard
6 Profile Edit

* **Note:** When User is signing up from Social accounts there will not be value for User-type. In this condition user will be automatically redirected to Profile Edit page.
* **Issues:**
1 #126
2 #131 

* **[Video](https://youtu.be/t0W6tdq0HPQ)**

### CODE REVIEW

**Comment by vnbang2003** [comment]
@ultimatecoder the dashboard url is wrong. right now url is /dashboard/ not /profile/dashboard/.
Even this code is gone break build as @theskumar Testcase assume post login url is /. To accept this LOGIN_REDIRECT_URL  we need to fix #131 .

**Comment by ultimatecoder** [comment]
@vnbang2003  I have redirected user to **/dashboard** rather then **/profile/dashboard**. The test case of sighup and login are up for rewriting again and it is not present in master. I request to reconstruct as a new issue once we finalize with the flow of the system. I have merged the issue #131 You can close this now. Thanks

**Comment by vnbang2003** [comment]
I have already open issue for fixing /dashboard/ link #131 . We are already having testcase failure due to with builds are failing. 
Two option
1) Fix the testcase right now
2) Diable testcase from build till we get update testcase.

@theskumar Please take final call on how do you want to proceed ?

**Comment by theskumar** [comment]
If possible update the TestCase otherwise disable it. Let's get the refactored logic in the `master` which is atleast tested manually.

**Comment by theskumar** [comment]
looking at the logs the it seems the tests didn't run at first place. I've restarted the test, it should fix the wrong reporting on this PR.

**Comment by theskumar** [comment]
I'm merging this in as all the test run fine on my local machine there seems to be issue with travis not able to fireup phantomjs. Will have a look at that later.

**Pull request merged**
