### PR TITLE
Sorting workshop list based on expected date #229

### PR DESCRIPTION
**Pull request by shubhamgupta2021**

### CODE REVIEW

**Comment by vnbang2003** [comment]
@shubhamgupta2021 Can you fix the test coverage issue it reducing by 0.5 percentage.

**Comment by shubhamgupta2021** [comment]
@vnbang2003 coveralls.io is asking for read access to my organisation repos as well, which I can't give. Can you please do this.

**Comment by vnbang2003** [comment]
Can you update this pull request with dummy change and see if that fixes the issue.

**Comment by shubhamgupta2021** [comment]
@vnbang2003, I have updated the test case, Please review.

**Pull request merged**
