### PR TITLE
Design

### PR DESCRIPTION
**Pull request by Praseetha-KR**
- Added gulp with SASS compilation, minification, autoprefix & sourcemaps
- Updated README on setup for frontend changes
- Basic theme & logo
- Added index page layout with placeholder text
- Styles for login/signup/password-reset forms

home_page

login_page

### CODE REVIEW

**Comment by harisibrahimkv** [comment]
Um, isn't `wye` just the name of the codebase? Or are we changing the name of the entire project from Python Express to wye?

**Comment by vnbang2003** [comment]
I like the designs.  
@harisibrahimkv 
Should we keep pythonexpress as name is good question?offline few people expressed pythonexpress  is not attractive name? I think we should decide in mailing list this to see if we can get better name.

**Comment by harisibrahimkv** [comment]
@vnbang2003 Let's put it in the mailing list. Why I asked was because if we are sticking to Python Express, then that logo might need to change.

**Comment by vnbang2003** [comment]
@harisibrahimkv I has suggested Praseetha over email to help us with logo for pythonexpress. Once she is comes up with logo for pythonexpress we can go ahead and change it but important is let get Base template design for work in UX/UI.

**Comment by harisibrahimkv** [comment]
@vnbang2003 Base template and design looks fantastic. :+1: 

I brought up this discussion just because I saw the `wye` logo on the template.

**Pull request merged**
