### PR TITLE
Wye #300 Add address fields for organisation

### PR DESCRIPTION
**Pull request by shankisg**
Address issue #300 
Added new field to capture full address, pincode and address map url. 

Note: 
    - In organisation details page map will be displayed if full address is provided.
    - Before deploying the changes in production, generate google map api key (enable it for Google Maps Embed API  and Google Maps JavaScript API )  and set GOOGLE_MAP_API key in environment.

### CODE REVIEW

**Comment by vnbang2003** [comment]
@kracekumar @vigneshsarma Let me know if you guys can generate "GOOGLE_MAP_API" like other key and set environment variable

**Comment by vnbang2003** [comment]
@shankisg Can you fix the build issue .

**Comment by shankisg** [comment]
@vnbang2003 I have fixed flake issue and also autocomplete include issue. Currently test case is failing in tests/functional/test_edit_profile.py::test_signup_flow 

In my local I run py.test and it was successful. Test log below.

tests/functional/test_add_org_member_flow.py::test_add_new_member_flow PASSED
tests/functional/test_add_org_member_flow.py::test_add_existing_member_flow PASSED
tests/functional/test_edit_profile.py::test_signup_flow PASSED
tests/functional/test_forgot_password_flow.py::test_forgot_password_flow PASSED
tests/functional/test_organsisation_flow.py::test_organisation_flow PASSED
tests/functional/test_organsisation_flow.py::test_org_edit_flow PASSED
tests/functional/test_regional_lead_flow.py::test_regional_lead_flow PASSED
tests/functional/test_user_flow.py::test_signup_flow PASSED
tests/functional/test_workshops_flow.py::test_workshop_flow FAILED
tests/functional/workshop/test_create_workshop.py::test_workshop_create PASSED
tests/functional/workshop/test_workshop_list.py::test_workshop_list PASSED
tests/integration/test_allowed_pages.py::test_public_pages PASSED
tests/integration/test_allowed_pages.py::test_staff_pages PASSED
tests/integration/test_allowed_pages.py::test_orgnisation_pages PASSED
tests/integration/test_allowed_pages.py::test_workshop_pages PASSED
tests/unit/test_signup_mobile_validation.py::test_invalid_mobile_number1 PASSED
tests/unit/test_signup_mobile_validation.py::test_invalid_mobile_number2 PASSED

**Comment by vnbang2003** [comment]
@shankisg  problem looks with with flake8 . You can look into build log
https://travis-ci.org/pythonindia/wye/builds/153505046

**Comment by vnbang2003** [comment]
@shankisg Finally build passed but test coverage is reduced. I will accept PR but can you please add more testcase for this change in new PR.

**Pull request merged**
