### PR TITLE
Dashboard throwing 500 when the user not loggedin

### PR DESCRIPTION
**Pull request by vigneshsarma**
There was a query to profile Model that was failing in this case, so now
throwing 404 instead.

```python
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "./wye/profiles/views.py", line 35, in dispatch
    user__id=self.request.user.id)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
```

### CODE REVIEW

**Comment by vnbang2003** [comment]
@vigneshsarma can you please fix the check failure ?

**Comment by vigneshsarma** [comment]
`flake8` error in `wye/reports/` seems to be the only real error. Others seem transient. 

What do you want to do with flake errors? Do you indent to use those files, in which case I will just update them with flake ignore, otherwise I can just delete the files entirely.

**Comment by theskumar** [comment]
It would be great to not to do flake ignore. There are tools available like autopep8 to fix the issues.

**Comment by vnbang2003** [comment]
@vigneshsarma let get Pep8 as it easy fix. If you using terminal you can do pep8 package and run it once.

**Pull request merged**
