### PR TITLE
Wye 125

### PR DESCRIPTION
**Pull request by shankisg**
Fix for #125 

Added create and update workshop flow fix, per requirement. 

Also contains fix for #138 

Datepicker was not working due to some changes done in base.html. I added fix for that in this pull also

### CODE REVIEW

**Comment by vnbang2003** [comment]
@shankisg We need to add testcase for workshop section as pur percentage is going down to 57.
Let me a point to do it soon. I will merge this request

**Comment by shankisg** [comment]
Ok

**Comment by shankisg** [comment]
fix implemented Commit #75ddd948ed6f231c13180d52776381ee2fe21000

**Comment by shankisg** [comment]
@vnbang2003 pls close this

**Pull request merged**
