### PR TITLE
Mandatory fields shown as asterisk while updating profile

### PR DESCRIPTION
**Pull request by ashu94**
#225 issue

### CODE REVIEW

**Comment by vnbang2003** [comment]
@ashu94 Please add test case for the change to be accept. Let add text check useless also to we maintain coverall number.

**Comment by ashu94** [comment]
have a look at it now

**Comment by ashu94** [comment]
@vnbang2003 have a look at it

**Comment by vnbang2003** [comment]
@ashu94 This good very good. I am merging this request.

**Pull request merged**
